# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BKD Scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BKD Scanner
  
  pod “TTRangeSlider”
  pod 'Alamofire'
  pod 'Toast'
  
  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
      
end

target 'Scan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BKD Scanner
  
  pod “TTRangeSlider”
  pod 'Alamofire'
  pod 'Toast'
  
  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
      
end


post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.3'
      end
    end
  end
end
